# This is an example yaml configuration for the storage of project metadata into the Svalbox server system
# Please do NOT remove any of the metadata keys (i.e., the words found in front of the ":" marker).
# Please make sure to fill out all fields. Where applicable, a list of items can be supplied as so:

# metadata_key_with_single_data: information goes here # comment with description here / single metadata
# metadata_key_with_multiple_data: # Comment still goes here, but additional items can be specified below after the dash structure (4 spaces, dash, 1 space, data entry)
#    - list item here
#    - second list item here
#    - third list item here
#    - etc.

## Project-level parameters:

# ArcGIS geodabase file to load - make sure to include absolute file paths and have it point to the geodatabase connection linked with the appropriate server:
geodatabase: C:\Users\Peter\Documents\ArcGIS\Projects\MyProject2\MyProject2.gdb # FILEDIR (absolute)

project_name: testing
project_name_short: tst
project_campaign: bla123
project_ris_id: 123541
project_unis_number: 921461
project_institution: 
    - UNIS
project_affiliation:
    - UiO
campaign_platform: 
    - tent # options include: tent, cabin, skis, foot, boat
campaign_responsible:
    - Peter Betlem
    - Kim Senger
campaign_assistant: 
    - Tom Birchall
campaign_start_date: 20190801
campaign_end_date: 20190905
campaign_grant:
    - 12315124
campaign_description: askjfdaskd
campaign_comment:
campaign_gpx_tracks: C:\Users\Peter\Documents\ArcGIS\Projects\MyProject2\mygpxtracks.zip # FILEDIR (absolute) with all gpx tracks zipped together
campaign_data:
    
